### ISSUE TITLE
how to get pocket protein files

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/XLPFE#3]
Hi,
First of all, thank you for freely making available to the scientific community the XLPFE code. I'd like to ask you about how the pocket protein pdb files for every proteins-ligand complexes contained into the data folder can be got.
Thank you very much in advance for your reply.

**Comment by LinaDongXMU** [comment]
Pymol, X-Tool and other softwares related to molecular modeling are able to get pocket.

**Comment by mglgc** [comment]
Thanks a lot for your prompt reply.
